# Generated by Django 6.1 on 2026-09-04 13:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_whistlist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Whistlist',
            new_name='Wishlist',
        ),
    ]
